spring.application.name=video-service

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.servlet.multipart.enabled=true

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

server.port=8082

aws.access-key=
aws.secret-key=
aws.region=
aws.s3.bucket-name=

management.endpoints.web.exposure.include=health,info